MegCC WebAssembly Support
MegEngine/MegCC pull request #57
Opened 2024-09-22 09:23 UTC by kqyhappy

2024-09-22 09:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MegEngine/MegCC?pullRequest=57) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MegEngine/MegCC?pullRequest=57) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MegEngine/MegCC?pullRequest=57) it.</sub>

2024-09-28 13:39 UTC, Li-Ming-xin requested changes

2024-09-28 13:39 UTC, Li-Ming-xin commented on runtime/example/WebAssembly/template.html
> +        }
需要添加用户打印和保存输出到文件的逻辑，确保用户可以拿到输出。

2024-10-11 02:52 UTC, Li-Ming-xin commented on compiler/lib/KernelGen/KernelGen.cpp
> +        web32_kerns.insert(web32_kerns.end(), gi_kerns.begin(), gi_kerns.end());
先不加gi_kerns了吧，gi 的 float16 不支持 x86 的指令集，因为我看 immigration/include/gi_float16.h 里只支持了 arm neon 和 risc-v rvv 指令集。

2024-10-11 03:02 UTC, Li-Ming-xin commented on compiler/lib/KernelGen/WebAssembly/InternalKernel/Fp32MatMulM4N12.cpp
> +#endif
如果未定义 `__SSE__` 宏这个函数的实现将为空，可以加个 `#else` 编译分支，在里面加上naive的实现或简单地使用 `#error "xxxxx"` 让进了 else 编译分支时编译失败。

2024-10-11 03:27 UTC, Li-Ming-xin commented on compiler/lib/KernelGen/WebAssembly/KernelPack.cpp
> +};
nit: 使用 namespace {} 将 `struct AllWebAssemblyKernel` 包裹起来

2024-10-11 07:56 UTC, Li-Ming-xin commented on compiler/lib/KernelGen/WebAssembly/InternalKernel/Fp32MatMulM4N12.cpp
> +#endif
ditto

2024-10-11 08:15 UTC, Li-Ming-xin commented on compiler/lib/KernelGen/WebAssembly/InternalKernel/InternalKernel.h
> +class WebAssemblyMatmulInternal : public InternalKernelFunc {
nit: 继承 `WebAssemblyInternalKernelFunc`？从语义上更为合适

2024-10-11 08:28 UTC, Li-Ming-xin commented on compiler/lib/KernelGen/WebAssembly/InternalKernel/Fp32MatMulM4N12.cpp
> +        if ((k + 3) >= K) break;
使用 switch case 且 fall through 的方式，可能比目前的 if 写法性能会更好一些。

2024-10-11 08:29 UTC, Li-Ming-xin commented on compiler/lib/KernelGen/WebAssembly/InternalKernel/Fp32MatMulM4N12.cpp
> +        if ((k + 3) >= K) break;
ditto

2024-10-11 08:31 UTC, Li-Ming-xin commented on compiler/lib/KernelGen/WebAssembly/InternalKernel/Fp32MatMulM4N12.cpp
> +                            break;
上面所说的 switch case 的写法就类似这里

2024-10-11 08:34 UTC, Li-Ming-xin commented on compiler/lib/KernelGen/WebAssembly/InternalKernel/Fp32MatMulM4N12.cpp
> +#endif
这个文件里很多类似的上面所说的需要添加编译宏 `#error` 的位置，可以检查一下，不一一列出了。

2024-10-11 08:42 UTC, Li-Ming-xin commented on compiler/lib/KernelGen/WebAssembly/MatMulKernel/FP32MatMulM4N12.cpp
> +    return true;
1. `return true` 删掉
2. internal matmul 应该没支持 bias 和 输入的 transpose？在这个函数把这些限制条件加上，不然一个输入transpose过的算子或者有bias的算子会使用这个算子实现，计算结果会有问题。

2024-10-11 09:02 UTC, Li-Ming-xin commented on runtime/example/WebAssembly/wasm_main.c
> +    return 0;
这个 `main` 函数是？

2024-10-11 09:20 UTC, Li-Ming-xin commented on runtime/src/parse.c
> +        printf(
将 `printf` 恢复到 `LOG_DEBUG`

2024-10-11 09:20 UTC, Li-Ming-xin commented on runtime/src/parse.c
> +    printf(
ditto

2024-10-22 12:01 UTC, kqyhappy commented on runtime/example/WebAssembly/wasm_main.c
> +    return 0;
可以没有，执行入口在infer

2024-10-22 12:01 UTC, kqyhappy commented on compiler/lib/KernelGen/WebAssembly/InternalKernel/Fp32MatMulM4N12.cpp
> +#endif
fix

2024-10-22 12:01 UTC, kqyhappy commented on compiler/lib/KernelGen/WebAssembly/InternalKernel/Fp32MatMulM4N12.cpp
> +                            break;
fix

2024-10-22 12:02 UTC, kqyhappy commented on compiler/lib/KernelGen/WebAssembly/InternalKernel/Fp32MatMulM4N12.cpp
> +        if ((k + 3) >= K) break;
将if break 代码块重构成了switch fall through

2024-10-22 12:02 UTC, kqyhappy commented on compiler/lib/KernelGen/WebAssembly/InternalKernel/Fp32MatMulM4N12.cpp
> +        if ((k + 3) >= K) break;
ditto

2024-10-22 12:02 UTC, kqyhappy commented on compiler/lib/KernelGen/WebAssembly/InternalKernel/InternalKernel.h
> +class WebAssemblyMatmulInternal : public InternalKernelFunc {
这个class没用到，在新commit里remove了

2024-10-22 12:02 UTC, kqyhappy commented on compiler/lib/KernelGen/WebAssembly/InternalKernel/Fp32MatMulM4N12.cpp
> +#endif
fix

2024-10-22 12:02 UTC, kqyhappy commented on compiler/lib/KernelGen/WebAssembly/KernelPack.cpp
> +};
fix

2024-10-22 12:03 UTC, kqyhappy commented on compiler/lib/KernelGen/WebAssembly/InternalKernel/Fp32MatMulM4N12.cpp
> +#endif
fix, add #else #error...

2024-10-22 12:03 UTC, kqyhappy commented on compiler/lib/KernelGen/KernelGen.cpp
> +        web32_kerns.insert(web32_kerns.end(), gi_kerns.begin(), gi_kerns.end());
fix, rm gi_kerns

2024-10-22 13:29 UTC, kqyhappy commented on runtime/example/WebAssembly/template.html
> +        }
add a download button

2024-10-22 13:29 UTC, kqyhappy commented on runtime/src/parse.c
> +    printf(
fix

2024-10-22 13:29 UTC, kqyhappy commented on runtime/src/parse.c
> +        printf(
fix

2024-10-22 13:37 UTC, kqyhappy commented on runtime/example/WebAssembly/template.html
> +        }
add a print flag

2024-10-23 02:34 UTC, Li-Ming-xin commented on compiler/lib/KernelGen/WebAssembly/MatMulKernel/FP32MatMulM4N12.cpp
> +    return true;
可以用 `context->getAttrInt("nr_operands") == 3`，因为带bias的话 nr_operands 为 4.

2024-10-23 02:39 UTC, Li-Ming-xin commented
others, LGTM.

2024-10-23 10:32 UTC, Li-Ming-xin approved these changes

2024-10-23 12:55 UTC, merged